//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.ServicioEjemploSoap")]
    public interface ServicioEjemploSoap {
        
        // CODEGEN: Generating message contract since element name productosResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/productos", ReplyAction="*")]
        WebApplication2.ServiceReference1.productosResponse productos(WebApplication2.ServiceReference1.productosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/productos", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.productosResponse> productosAsync(WebApplication2.ServiceReference1.productosRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/comprar", ReplyAction="*")]
        WebApplication2.ServiceReference1.comprarResponse comprar(WebApplication2.ServiceReference1.comprarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/comprar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.comprarResponse> comprarAsync(WebApplication2.ServiceReference1.comprarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class productosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="productos", Namespace="http://localhost/", Order=0)]
        public WebApplication2.ServiceReference1.productosRequestBody Body;
        
        public productosRequest() {
        }
        
        public productosRequest(WebApplication2.ServiceReference1.productosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class productosRequestBody {
        
        public productosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class productosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="productosResponse", Namespace="http://localhost/", Order=0)]
        public WebApplication2.ServiceReference1.productosResponseBody Body;
        
        public productosResponse() {
        }
        
        public productosResponse(WebApplication2.ServiceReference1.productosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class productosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productosResult;
        
        public productosResponseBody() {
        }
        
        public productosResponseBody(string productosResult) {
            this.productosResult = productosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprar", Namespace="http://localhost/", Order=0)]
        public WebApplication2.ServiceReference1.comprarRequestBody Body;
        
        public comprarRequest() {
        }
        
        public comprarRequest(WebApplication2.ServiceReference1.comprarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class comprarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string producto;
        
        public comprarRequestBody() {
        }
        
        public comprarRequestBody(string producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarResponse", Namespace="http://localhost/", Order=0)]
        public WebApplication2.ServiceReference1.comprarResponseBody Body;
        
        public comprarResponse() {
        }
        
        public comprarResponse(WebApplication2.ServiceReference1.comprarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class comprarResponseBody {
        
        public comprarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioEjemploSoapChannel : WebApplication2.ServiceReference1.ServicioEjemploSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEjemploSoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.ServicioEjemploSoap>, WebApplication2.ServiceReference1.ServicioEjemploSoap {
        
        public ServicioEjemploSoapClient() {
        }
        
        public ServicioEjemploSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEjemploSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEjemploSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEjemploSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.productosResponse WebApplication2.ServiceReference1.ServicioEjemploSoap.productos(WebApplication2.ServiceReference1.productosRequest request) {
            return base.Channel.productos(request);
        }
        
        public string productos() {
            WebApplication2.ServiceReference1.productosRequest inValue = new WebApplication2.ServiceReference1.productosRequest();
            inValue.Body = new WebApplication2.ServiceReference1.productosRequestBody();
            WebApplication2.ServiceReference1.productosResponse retVal = ((WebApplication2.ServiceReference1.ServicioEjemploSoap)(this)).productos(inValue);
            return retVal.Body.productosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.productosResponse> WebApplication2.ServiceReference1.ServicioEjemploSoap.productosAsync(WebApplication2.ServiceReference1.productosRequest request) {
            return base.Channel.productosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.productosResponse> productosAsync() {
            WebApplication2.ServiceReference1.productosRequest inValue = new WebApplication2.ServiceReference1.productosRequest();
            inValue.Body = new WebApplication2.ServiceReference1.productosRequestBody();
            return ((WebApplication2.ServiceReference1.ServicioEjemploSoap)(this)).productosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.comprarResponse WebApplication2.ServiceReference1.ServicioEjemploSoap.comprar(WebApplication2.ServiceReference1.comprarRequest request) {
            return base.Channel.comprar(request);
        }
        
        public void comprar(string producto) {
            WebApplication2.ServiceReference1.comprarRequest inValue = new WebApplication2.ServiceReference1.comprarRequest();
            inValue.Body = new WebApplication2.ServiceReference1.comprarRequestBody();
            inValue.Body.producto = producto;
            WebApplication2.ServiceReference1.comprarResponse retVal = ((WebApplication2.ServiceReference1.ServicioEjemploSoap)(this)).comprar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.comprarResponse> WebApplication2.ServiceReference1.ServicioEjemploSoap.comprarAsync(WebApplication2.ServiceReference1.comprarRequest request) {
            return base.Channel.comprarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.comprarResponse> comprarAsync(string producto) {
            WebApplication2.ServiceReference1.comprarRequest inValue = new WebApplication2.ServiceReference1.comprarRequest();
            inValue.Body = new WebApplication2.ServiceReference1.comprarRequestBody();
            inValue.Body.producto = producto;
            return ((WebApplication2.ServiceReference1.ServicioEjemploSoap)(this)).comprarAsync(inValue);
        }
    }
}
